# Generated by Django 5.0.6 on 2024-05-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_remove_cliente_user_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='assets/uploads/clientes'),
        ),
    ]
