# Generated by Django 5.0.6 on 2024-05-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_alter_cliente_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.ImageField(blank=True, upload_to='assets/uploads/clientes'),
        ),
    ]
