# Generated by Django 5.0.6 on 2024-05-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0004_alter_producto_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='uploads/clientes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_url',
            field=models.ImageField(blank=True, upload_to='uploads/clientes'),
        ),
    ]
