# Generated by Django 5.0.6 on 2024-05-27 06:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_remove_cupon_tipo_remove_cupon_usado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cupon',
            name='usado_por',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
