# Generated by Django 5.0.6 on 2024-06-02 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0010_remove_cliente_contraseña_cliente_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='ultimo_login',
        ),
    ]
