# Generated by Django 5.0.6 on 2024-06-03 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0011_remove_cliente_ultimo_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='usado_por',
        ),
        migrations.AddField(
            model_name='cupon',
            name='cliente_que_lo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_utilizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
