# Generated by Django 5.0.6 on 2024-06-04 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0012_remove_cupon_usado_por_cupon_cliente_que_lo_uso'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='assets/uploads/categorias')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='dashboards.categoria')),
            ],
        ),
    ]
