# Generated by Django 5.0.6 on 2024-06-04 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0013_categoriaimagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default='assets/uploads/productos/3.jpg', upload_to='assets/uploads/categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(default=0, upload_to='assets/uploads/marcas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cupon',
            name='cliente_que_lo_uso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_utilizados', to='dashboards.cliente'),
        ),
        migrations.DeleteModel(
            name='CategoriaImagen',
        ),
    ]
