# Generated by Django 5.0.6 on 2024-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_de_registro',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
