# Generated by Django 5.0.6 on 2024-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0016_remove_cliente_fecha_de_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='orden_asociada',
        ),
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
