# Generated by Django 5.0.6 on 2024-06-11 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_rename_precio_unitario_detallecarrito_preciounitario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='fecha_creacion',
            new_name='creado_en',
        ),
        migrations.RenameField(
            model_name='detallecarrito',
            old_name='precioUnitario',
            new_name='precio_unitario',
        ),
        migrations.RenameField(
            model_name='orden',
            old_name='fecha',
            new_name='creado_en',
        ),
        migrations.AddField(
            model_name='orden',
            name='direccion_entrega',
            field=models.TextField(default=2424),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orden',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=100),
        ),
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.CharField(default=2024, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.cliente'),
        ),
        migrations.AlterField(
            model_name='detallecarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboards.cliente'),
        ),
    ]
