# Generated by Django 5.0.6 on 2024-06-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboards', '0021_cliente_groups_cliente_is_active_cliente_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='groups',
            field=models.ManyToManyField(related_name='clientes', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='assets/uploads/clientes'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user_permissions',
            field=models.ManyToManyField(related_name='clientes', to='auth.permission'),
        ),
    ]
