# Generated by Django 5.0.6 on 2024-06-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboards', '0024_alter_cliente_apellido_alter_cliente_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='auth.permission'),
        ),
    ]
