# Generated by Django 5.0.6 on 2024-06-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0026_remove_carrito_total_remove_detallecarrito_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='direccion_entrega',
        ),
        migrations.RemoveField(
            model_name='orden',
            name='estado',
        ),
        migrations.AddField(
            model_name='carrito',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
