# Generated by Django 5.0.6 on 2024-06-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0029_alter_categoria_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(upload_to='assets/uploads/categorias'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imagen',
            field=models.ImageField(upload_to='assets/uploads/marcas'),
        ),
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to='assets\\uploads\\productos'),
        ),
    ]
