# Generated by Django 5.0.6 on 2024-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0030_alter_categoria_imagen_alter_marca_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to='\\assets\\uploads\\productos'),
        ),
    ]
