# Generated by Django 5.0.6 on 2024-06-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0031_alter_productoimagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoimagen',
            name='imagen',
            field=models.ImageField(upload_to='assets/uploads/productos'),
        ),
    ]
